;;; christmas-theme.el --- Christmas Theme

;; Copyright 2015-present, All rights reserved
;;
;; Code licensed under the MIT license

;; Author: film42
;; Version: 1.5.1
;; Package-Requires: ((emacs "24"))
;; URL: https://github.com/christmas/emacs

;;; Commentary:

;; A dark color theme available for a number of editors.

;;; Code:
(require 'cl-lib)
(deftheme christmas)

;; Assigment form: VARIABLE COLOR [TTY-COLOR]
(let ((colors '(;; Upstream theme color
                (christmas-bg      "#170f10" "#000000") ; official background
                (christmas-current "#945e55") ; official current-line/selection
                (christmas-fg      "#c2c7c4") ; official foreground
                (christmas-comment "#7c807b") ; official comment
                (christmas-cyan    "#855450") ; official cyan
                (christmas-green   "#768673") ; official green
                (christmas-orange  "#7d4d45") ; official orange
                (christmas-pink    "#5e4248") ; official pink
                (christmas-purple  "#6e746f") ; official purple
                (christmas-red     "#945e55") ; official red
                (christmas-yellow  "#9da69e") ; official yellow
                ;; Other colors
                (bg2             "#5e4248")
                (bg3             "#170f10")
                (bg4             "#86938e")
                (fg2             "#b3beb7")
                (fg3             "#9fa9a6")
                (fg4             "#667070")
                (other-blue      "#59615e")))
      (faces '(;; default
               (cursor :background ,fg3)
               (default :background ,christmas-bg :foreground ,christmas-fg)
               (default-italic :slant italic)
               (ffap :foreground ,fg4)
               (fringe :background ,christmas-bg :foreground ,fg4)
               (highlight :foreground ,fg3 :background ,bg3)
               (hl-line :background ,christmas-current :extend t)
               (info-quoted-name :foreground ,christmas-orange)
               (info-string :foreground ,christmas-yellow)
               (lazy-highlight :foreground ,fg2 :background ,bg3)
               (link :foreground ,christmas-cyan :underline t)
               (linum :slant italic :foreground ,bg4 :background ,christmas-bg)
               (line-number :slant italic :foreground ,bg4 :background ,christmas-bg)
               (minibuffer-prompt :weight bold :foreground ,christmas-pink)
               (region :background ,christmas-yellow :foreground ,christmas-bg :extend t)
               (trailing-whitespace :foreground nil :background ,christmas-orange)
               (vertical-border :foreground ,bg2)
               (warning :foreground ,christmas-orange)
               (header-line :background ,christmas-bg)
               ;; syntax
               (font-lock-builtin-face :foreground ,christmas-orange)
               (font-lock-comment-face :foreground ,christmas-comment)
               (font-lock-comment-delimiter-face :foreground ,christmas-comment)
               (font-lock-constant-face :foreground ,christmas-cyan)
               (font-lock-doc-face :foreground ,christmas-comment)
               (font-lock-function-name-face :foreground ,christmas-green :weight bold)
               (font-lock-keyword-face :weight bold :foreground ,christmas-pink)
               (font-lock-negation-char-face :foreground ,christmas-cyan)
               (font-lock-preprocessor-face :foreground ,christmas-orange)
               (font-lock-reference-face :foreground ,christmas-cyan)
               (font-lock-regexp-grouping-backslash :foreground ,christmas-cyan)
               (font-lock-regexp-grouping-construct :foreground ,christmas-purple)
               (font-lock-string-face :foreground ,christmas-yellow)
               (font-lock-type-face :foreground ,christmas-purple)
               (font-lock-variable-name-face :foreground ,christmas-fg
                                             :weight bold)
               (font-lock-warning-face :foreground ,christmas-orange :background ,bg2)
               ;; auto-complete
               (ac-completion-face :underline t :foreground ,christmas-pink)
               ;; company
               (company-echo-common :foreground ,christmas-bg :background ,christmas-fg)
               (company-preview :background ,christmas-bg :foreground ,other-blue)
               (company-preview-common :foreground ,bg2 :foreground ,fg3)
               (company-preview-search :foreground ,christmas-purple :background ,christmas-bg)
               (company-scrollbar-bg :background ,bg3)
               (company-scrollbar-fg :foreground ,christmas-pink)
               (company-template-field :inherit region)
               (company-tooltip :foreground ,fg2 :background ,christmas-bg :weight bold)
               (company-tooltip-annotation :foreground ,christmas-cyan)
               (company-tooltip-common :foreground ,fg3)
               (company-tooltip-common-selection :foreground ,christmas-yellow)
               (company-tooltip-mouse :inherit highlight)
               (company-tooltip-selection :background ,bg3 :foreground ,fg3)
               ;; diff-hl
               (diff-hl-change :foreground ,christmas-orange :background ,christmas-orange)
               (diff-hl-delete :foreground ,christmas-red :background ,christmas-red)
               (diff-hl-insert :foreground ,christmas-green :background ,christmas-green)
               ;; dired
               (dired-directory :foreground ,christmas-green :weight normal)
               (dired-flagged :foreground ,christmas-pink)
               (dired-header :foreground ,fg3 :background ,christmas-bg)
               (dired-ignored :inherit shadow)
               (dired-mark :foreground ,christmas-fg :weight bold)
               (dired-marked :foreground ,christmas-orange :weight bold)
               (dired-perm-write :foreground ,fg3 :underline t)
               (dired-symlink :foreground ,christmas-yellow :weight normal :slant italic)
               (dired-warning :foreground ,christmas-orange :underline t)
               (diredp-compressed-file-name :foreground ,fg3)
               (diredp-compressed-file-suffix :foreground ,fg4)
               (diredp-date-time :foreground ,christmas-fg)
               (diredp-deletion-file-name :foreground ,christmas-pink :background ,christmas-current)
               (diredp-deletion :foreground ,christmas-pink :weight bold)
               (diredp-dir-heading :foreground ,fg2 :background ,bg4)
               (diredp-dir-name :inherit dired-directory)
               (diredp-dir-priv :inherit dired-directory)
               (diredp-executable-tag :foreground ,christmas-orange)
               (diredp-file-name :foreground ,christmas-fg)
               (diredp-file-suffix :foreground ,fg4)
               (diredp-flag-mark-line :foreground ,fg2 :slant italic :background ,christmas-current)
               (diredp-flag-mark :foreground ,fg2 :weight bold :background ,christmas-current)
               (diredp-ignored-file-name :foreground ,christmas-fg)
               (diredp-mode-line-flagged :foreground ,christmas-orange)
               (diredp-mode-line-marked :foreground ,christmas-orange)
               (diredp-no-priv :foreground ,christmas-fg)
               (diredp-number :foreground ,christmas-cyan)
               (diredp-other-priv :foreground ,christmas-orange)
               (diredp-rare-priv :foreground ,christmas-orange)
               (diredp-read-priv :foreground ,christmas-purple)
               (diredp-write-priv :foreground ,christmas-pink)
               (diredp-exec-priv :foreground ,christmas-yellow)
               (diredp-symlink :foreground ,christmas-orange)
               (diredp-link-priv :foreground ,christmas-orange)
               (diredp-autofile-name :foreground ,christmas-yellow)
               (diredp-tagged-autofile-name :foreground ,christmas-yellow)
               ;; enh-ruby
               (enh-ruby-heredoc-delimiter-face :foreground ,christmas-yellow)
               (enh-ruby-op-face :foreground ,christmas-pink)
               (enh-ruby-regexp-delimiter-face :foreground ,christmas-yellow)
               (enh-ruby-string-delimiter-face :foreground ,christmas-yellow)
               ;; font-latex
               (font-latex-bold-face :foreground ,christmas-purple)
               (font-latex-italic-face :foreground ,christmas-pink :slant italic)
               (font-latex-match-reference-keywords :foreground ,christmas-cyan)
               (font-latex-match-variable-keywords :foreground ,christmas-fg)
               (font-latex-string-face :foreground ,christmas-yellow)
               ;; gnus-group
               (gnus-group-mail-1 :foreground ,christmas-pink :weight bold)
               (gnus-group-mail-1-empty :inherit gnus-group-mail-1 :weight normal)
               (gnus-group-mail-2 :foreground ,christmas-cyan :weight bold)
               (gnus-group-mail-2-empty :inherit gnus-group-mail-2 :weight normal)
               (gnus-group-mail-3 :foreground ,christmas-comment :weight bold)
               (gnus-group-mail-3-empty :inherit gnus-group-mail-3 :weight normal)
               (gnus-group-mail-low :foreground ,christmas-current :weight bold)
               (gnus-group-mail-low-empty :inherit gnus-group-mail-low :weight normal)
               (gnus-group-news-1 :foreground ,christmas-pink :weight bold)
               (gnus-group-news-1-empty :inherit gnus-group-news-1 :weight normal)
               (gnus-group-news-2 :foreground ,christmas-cyan :weight bold)
               (gnus-group-news-2-empty :inherit gnus-group-news-2 :weight normal)
               (gnus-group-news-3 :foreground ,christmas-comment :weight bold)
               (gnus-group-news-3-empty :inherit gnus-group-news-3 :weight normal)
               (gnus-group-news-4 :inherit gnus-group-news-low)
               (gnus-group-news-4-empty :inherit gnus-group-news-low-empty)
               (gnus-group-news-5 :inherit gnus-group-news-low)
               (gnus-group-news-5-empty :inherit gnus-group-news-low-empty)
               (gnus-group-news-6 :inherit gnus-group-news-low)
               (gnus-group-news-6-empty :inherit gnus-group-news-low-empty)
               (gnus-group-news-low :foreground ,christmas-current :weight bold)
               (gnus-group-news-low-empty :inherit gnus-group-news-low :weight normal)
               (gnus-header-content :foreground ,christmas-pink)
               (gnus-header-from :foreground ,christmas-fg)
               (gnus-header-name :foreground ,christmas-purple)
               (gnus-header-subject :foreground ,christmas-green :weight bold)
               (gnus-summary-markup-face :foreground ,christmas-cyan)
               (gnus-summary-high-unread :foreground ,christmas-pink :weight bold)
               (gnus-summary-high-read :inherit gnus-summary-high-unread :weight normal)
               (gnus-summary-high-ancient :inherit gnus-summary-high-read)
               (gnus-summary-high-ticked :inherit gnus-summary-high-read :underline t)
               (gnus-summary-normal-unread :foreground ,other-blue :weight bold)
               (gnus-summary-normal-read :inherit gnus-summary-normal-unread :weight normal)
               (gnus-summary-normal-ancient :inherit gnus-summary-normal-read)
               (gnus-summary-normal-ticked :inherit gnus-summary-normal-read :underline t)
               (gnus-summary-low-unread :foreground ,christmas-comment :weight bold)
               (gnus-summary-low-read :inherit gnus-summary-low-unread :weight normal)
               (gnus-summary-low-ancient :inherit gnus-summary-low-read)
               (gnus-summary-low-ticked :inherit gnus-summary-low-read :underline t)
               (gnus-summary-selected :inverse-video t)
               ;; haskell-mode
               (haskell-operator-face :foreground ,christmas-pink)
               (haskell-constructor-face :foreground ,christmas-purple)
               ;; helm
               (helm-bookmark-w3m :foreground ,christmas-purple)
               (helm-buffer-not-saved :foreground ,christmas-purple :background ,christmas-bg)
               (helm-buffer-process :foreground ,christmas-orange :background ,christmas-bg)
               (helm-buffer-saved-out :foreground ,christmas-fg :background ,christmas-bg)
               (helm-buffer-size :foreground ,christmas-fg :background ,christmas-bg)
               (helm-candidate-number :foreground ,christmas-bg :background ,christmas-fg)
               (helm-ff-directory :foreground ,christmas-green :background ,christmas-bg :weight bold)
               (helm-ff-executable :foreground ,other-blue :background ,christmas-bg :weight normal)
               (helm-ff-file :foreground ,christmas-fg :background ,christmas-bg :weight normal)
               (helm-ff-invalid-symlink :foreground ,christmas-pink :background ,christmas-bg :weight bold)
               (helm-ff-prefix :foreground ,christmas-bg :background ,christmas-pink :weight normal)
               (helm-ff-symlink :foreground ,christmas-pink :background ,christmas-bg :weight bold)
               (helm-grep-cmd-line :foreground ,christmas-fg :background ,christmas-bg)
               (helm-grep-file :foreground ,christmas-fg :background ,christmas-bg)
               (helm-grep-finish :foreground ,fg2 :background ,christmas-bg)
               (helm-grep-lineno :foreground ,christmas-fg :background ,christmas-bg)
               (helm-grep-match :foreground nil :background nil :inherit helm-match)
               (helm-grep-running :foreground ,christmas-green :background ,christmas-bg)
               (helm-header :foreground ,fg2 :background ,christmas-bg :underline nil :box nil)
               (helm-moccur-buffer :foreground ,christmas-green :background ,christmas-bg)
               (helm-selection :background ,bg2 :underline nil)
               (helm-selection-line :background ,bg2)
               (helm-separator :foreground ,christmas-purple :background ,christmas-bg)
               (helm-source-go-package-godoc-description :foreground ,christmas-yellow)
               (helm-source-header :foreground ,christmas-pink :background ,christmas-bg :underline nil :weight bold)
               (helm-time-zone-current :foreground ,christmas-orange :background ,christmas-bg)
               (helm-time-zone-home :foreground ,christmas-purple :background ,christmas-bg)
               (helm-visible-mark :foreground ,christmas-bg :background ,bg3)
               ;; highlight-indentation minor mode
               (highlight-indentation-face :background ,bg2)
               ;; icicle
               (icicle-whitespace-highlight :background ,christmas-fg)
               (icicle-special-candidate :foreground ,fg2)
               (icicle-extra-candidate :foreground ,fg2)
               (icicle-search-main-regexp-others :foreground ,christmas-fg)
               (icicle-search-current-input :foreground ,christmas-pink)
               (icicle-search-context-level-8 :foreground ,christmas-orange)
               (icicle-search-context-level-7 :foreground ,christmas-orange)
               (icicle-search-context-level-6 :foreground ,christmas-orange)
               (icicle-search-context-level-5 :foreground ,christmas-orange)
               (icicle-search-context-level-4 :foreground ,christmas-orange)
               (icicle-search-context-level-3 :foreground ,christmas-orange)
               (icicle-search-context-level-2 :foreground ,christmas-orange)
               (icicle-search-context-level-1 :foreground ,christmas-orange)
               (icicle-search-main-regexp-current :foreground ,christmas-fg)
               (icicle-saved-candidate :foreground ,christmas-fg)
               (icicle-proxy-candidate :foreground ,christmas-fg)
               (icicle-mustmatch-completion :foreground ,christmas-purple)
               (icicle-multi-command-completion :foreground ,fg2 :background ,bg2)
               (icicle-msg-emphasis :foreground ,christmas-green)
               (icicle-mode-line-help :foreground ,fg4)
               (icicle-match-highlight-minibuffer :foreground ,christmas-orange)
               (icicle-match-highlight-Completions :foreground ,christmas-green)
               (icicle-key-complete-menu-local :foreground ,christmas-fg)
               (icicle-key-complete-menu :foreground ,christmas-fg)
               (icicle-input-completion-fail-lax :foreground ,christmas-pink)
               (icicle-input-completion-fail :foreground ,christmas-pink)
               (icicle-historical-candidate-other :foreground ,christmas-fg)
               (icicle-historical-candidate :foreground ,christmas-fg)
               (icicle-current-candidate-highlight :foreground ,christmas-orange :background ,bg3)
               (icicle-Completions-instruction-2 :foreground ,fg4)
               (icicle-Completions-instruction-1 :foreground ,fg4)
               (icicle-completion :foreground ,christmas-fg)
               (icicle-complete-input :foreground ,christmas-orange)
               (icicle-common-match-highlight-Completions :foreground ,christmas-purple)
               (icicle-candidate-part :foreground ,christmas-fg)
               (icicle-annotation :foreground ,fg4)
               ;; icomplete
               (icompletep-determined :foreground ,christmas-orange)
               ;; ido
               (ido-first-match :foreground ,christmas-pink :weight bold)
               (ido-only-match :foreground ,christmas-orange)
               (ido-subdir :foreground ,christmas-orange)
               (ido-virtual :foreground ,christmas-cyan)
               (ido-incomplete-regexp :inherit font-lock-warning-face)
               (ido-indicator :foreground ,christmas-fg :background ,christmas-pink)
               ;; isearch
               (isearch :weight bold :foreground ,christmas-orange :background ,bg3)
               (isearch-fail :foreground ,christmas-bg :background ,christmas-orange)
               ;; jde-java
               (jde-java-font-lock-constant-face :foreground ,christmas-cyan)
               (jde-java-font-lock-modifier-face :foreground ,christmas-pink)
               (jde-java-font-lock-number-face :foreground ,christmas-fg)
               (jde-java-font-lock-package-face :foreground ,christmas-fg)
               (jde-java-font-lock-private-face :foreground ,christmas-pink)
               (jde-java-font-lock-public-face :foreground ,christmas-pink)
               ;; js2-mode
               (js2-external-variable :foreground ,christmas-purple)
               (js2-function-param :foreground ,christmas-cyan)
               (js2-jsdoc-html-tag-delimiter :foreground ,christmas-yellow)
               (js2-jsdoc-html-tag-name :foreground ,other-blue)
               (js2-jsdoc-value :foreground ,christmas-yellow)
               (js2-private-function-call :foreground ,christmas-cyan)
               (js2-private-member :foreground ,fg3)
               ;; js3-mode
               (js3-error-face :underline ,christmas-orange)
               (js3-external-variable-face :foreground ,christmas-fg)
               (js3-function-param-face :foreground ,christmas-pink)
               (js3-instance-member-face :foreground ,christmas-cyan)
               (js3-jsdoc-tag-face :foreground ,christmas-pink)
               (js3-warning-face :underline ,christmas-pink)
               ;; magit
               (magit-branch :foreground ,christmas-cyan :weight bold)
               (magit-diff-context-highlight :background ,bg3 :foreground ,fg3)
               (magit-diff-file-header :foreground ,fg2 :background ,bg3)
               (magit-diffstat-added :foreground ,christmas-purple)
               (magit-diffstat-removed :foreground ,christmas-fg)
               (magit-hash :foreground ,fg2)
               (magit-hunk-heading :background ,bg3)
               (magit-hunk-heading-highlight :background ,bg3)
               (magit-item-highlight :background ,bg3)
               (magit-log-author :foreground ,fg3)
               (magit-process-ng :foreground ,christmas-orange :weight bold)
               (magit-process-ok :foreground ,christmas-green :weight bold)
               (magit-section-heading :foreground ,christmas-pink :weight bold)
               (magit-section-highlight :background ,bg2)
               ;; message
               (message-mml :foreground ,christmas-green :weight normal)
               (message-header-xheader :foreground ,christmas-cyan :weight normal)
               ;; mode-line
               (mode-line :foreground nil :background ,christmas-current :box ,christmas-current)
               (mode-line-inactive :foreground ,christmas-fg :background ,bg2 :box ,bg2)
               ;; mu4e
               (mu4e-unread-face :foreground ,christmas-pink :weight normal)
               (mu4e-view-url-number-face :foreground ,christmas-purple)
               (mu4e-highlight-face :background ,christmas-bg
                                    :foreground ,christmas-yellow)
               (mu4e-header-highlight-face :background ,christmas-current
                                           :foreground ,christmas-fg
                                           :underline nil :weight bold)
               (mu4e-header-key-face :inherit message-mml)
               (mu4e-header-marks-face :foreground ,christmas-purple)
               (mu4e-cited-1-face :foreground ,christmas-purple)
               (mu4e-cited-2-face :foreground ,christmas-orange)
               (mu4e-cited-3-face :foreground ,christmas-comment)
               (mu4e-cited-4-face :foreground ,fg2)
               (mu4e-cited-5-face :foreground ,fg3)
               ;; org
               (org-agenda-date :foreground ,christmas-cyan :underline nil)
               (org-agenda-dimmed-todo-face :foreground ,christmas-comment)
               (org-agenda-done :foreground ,christmas-green)
               (org-agenda-structure :foreground ,christmas-purple)
               (org-block :foreground ,christmas-orange)
               (org-code :foreground ,christmas-yellow)
               (org-column :background ,bg4)
               (org-column-title :inherit org-column :weight bold :underline t)
               (org-date :foreground ,christmas-cyan :underline t)
               (org-document-info :foreground ,other-blue)
               (org-document-info-keyword :foreground ,christmas-comment)
               (org-document-title :weight bold :foreground ,christmas-orange :height 1.44)
               (org-done :foreground ,christmas-green)
               (org-ellipsis :foreground ,christmas-comment)
               (org-footnote :foreground ,other-blue)
               (org-formula :foreground ,christmas-pink)
               (org-headline-done :foreground ,christmas-comment :weight normal :strike-through t)
               (org-hide :foreground ,christmas-bg :background ,christmas-bg)
               (org-level-1 :inherit bold :foreground ,christmas-pink :height 1.3)
               (org-level-2 :inherit bold :foreground ,christmas-purple :height 1.1)
               (org-level-3 :weight normal :foreground ,christmas-green :height 1.0)
               (org-level-4 :weight normal :foreground ,christmas-yellow)
               (org-level-5 :weight normal :foreground ,christmas-cyan)
               (org-level-6 :weight normal :foreground ,christmas-orange)
               (org-level-7 :weight normal :foreground ,other-blue)
               (org-level-8 :weight normal :foreground ,christmas-fg)
               (org-link :foreground ,christmas-cyan :underline t)
               (org-priority :foreground ,christmas-cyan)
               (org-scheduled :foreground ,christmas-green)
               (org-scheduled-previously :foreground ,christmas-yellow)
               (org-scheduled-today :foreground ,christmas-green)
               (org-sexp-date :foreground ,fg4)
               (org-special-keyword :foreground ,christmas-yellow)
               (org-table :foreground ,christmas-purple)
               (org-tag :foreground ,christmas-pink :weight bold :background ,bg2)
               (org-todo :foreground ,christmas-orange :weight bold :background ,bg2)
               (org-upcoming-deadline :foreground ,christmas-yellow)
               (org-warning :weight bold :foreground ,christmas-pink)
               ;; outline
               (outline-1 :foreground ,christmas-green)
               (outline-2 :foreground ,christmas-purple)
               (outline-3 :foreground ,christmas-cyan)
               (outline-4 :foreground ,christmas-orange)
               (outline-5 :foreground ,christmas-orange)
               (outline-6 :foreground ,other-blue)
               ;; powerline
               (powerline-evil-base-face :foreground ,bg2)
               (powerline-evil-emacs-face :inherit powerline-evil-base-face :background ,christmas-yellow)
               (powerline-evil-insert-face :inherit powerline-evil-base-face :background ,christmas-cyan)
               (powerline-evil-motion-face :inherit powerline-evil-base-face :background ,christmas-purple)
               (powerline-evil-normal-face :inherit powerline-evil-base-face :background ,christmas-green)
               (powerline-evil-operator-face :inherit powerline-evil-base-face :background ,christmas-pink)
               (powerline-evil-replace-face :inherit powerline-evil-base-face :background ,christmas-red)
               (powerline-evil-visual-face :inherit powerline-evil-base-face :background ,christmas-orange)
               ;; rainbow-delimiters
               (rainbow-delimiters-depth-1-face :foreground ,christmas-fg)
               (rainbow-delimiters-depth-2-face :foreground ,christmas-cyan)
               (rainbow-delimiters-depth-3-face :foreground ,christmas-purple)
               (rainbow-delimiters-depth-4-face :foreground ,christmas-pink)
               (rainbow-delimiters-depth-5-face :foreground ,christmas-orange)
               (rainbow-delimiters-depth-6-face :foreground ,christmas-green)
               (rainbow-delimiters-depth-7-face :foreground ,christmas-yellow)
               (rainbow-delimiters-depth-8-face :foreground ,other-blue)
               (rainbow-delimiters-unmatched-face :foreground ,christmas-orange)
               ;; rpm-spec
               (rpm-spec-dir-face :foreground ,christmas-green)
               (rpm-spec-doc-face :foreground ,christmas-pink)
               (rpm-spec-ghost-face :foreground ,christmas-purple)
               (rpm-spec-macro-face :foreground ,christmas-yellow)
               (rpm-spec-obsolete-tag-face :inherit font-lock-warning-face)
               (rpm-spec-package-face :foreground ,christmas-purple)
               (rpm-spec-section-face :foreground ,christmas-yellow)
               (rpm-spec-tag-face :foreground ,christmas-cyan)
               (rpm-spec-var-face :foreground ,christmas-orange)
               ;; show-paren
               (show-paren-match-face :background unspecified
                                      :foreground ,christmas-cyan
                                      :weight bold)
               (show-paren-match :background unspecified
                                 :foreground ,christmas-cyan
                                 :weight bold)
               (show-paren-match-expression :inherit region)
               (show-paren-mismatch :inherit font-lock-warning-face)
               ;; slime
               (slime-repl-inputed-output-face :foreground ,christmas-purple)
               ;; spam
               (spam :inherit gnus-summary-normal-read :foreground ,christmas-orange
                     :strike-through t :slant oblique)
               ;; term
               (term :foreground ,christmas-fg :background ,christmas-bg)
               (term-color-black :foreground ,bg3 :background ,bg3)
               (term-color-blue :foreground ,christmas-purple :background ,christmas-purple)
               (term-color-cyan :foreground ,christmas-cyan :background ,christmas-cyan)
               (term-color-green :foreground ,christmas-green :background ,christmas-green)
               (term-color-magenta :foreground ,christmas-pink :background ,christmas-pink)
               (term-color-red :foreground ,christmas-red :background ,christmas-red)
               (term-color-white :foreground ,fg2 :background ,fg2)
               (term-color-yellow :foreground ,christmas-yellow :background ,christmas-yellow)
               ;; undo-tree
               (undo-tree-visualizer-current-face :foreground ,christmas-orange)
               (undo-tree-visualizer-default-face :foreground ,fg2)
               (undo-tree-visualizer-register-face :foreground ,christmas-purple)
               (undo-tree-visualizer-unmodified-face :foreground ,christmas-fg)
               ;; web-mode
               (web-mode-builtin-face :inherit ,font-lock-builtin-face)
               (web-mode-comment-face :inherit ,font-lock-comment-face)
               (web-mode-constant-face :inherit ,font-lock-constant-face)
               (web-mode-doctype-face :inherit ,font-lock-comment-face)
               (web-mode-function-name-face :inherit ,font-lock-function-name-face)
               (web-mode-html-attr-name-face :foreground ,christmas-purple)
               (web-mode-html-attr-value-face :foreground ,christmas-green)
               (web-mode-html-tag-face :foreground ,christmas-pink :weight bold)
               (web-mode-keyword-face :foreground ,christmas-pink)
               (web-mode-string-face :foreground ,christmas-yellow)
               (web-mode-type-face :inherit ,font-lock-type-face)
               (web-mode-warning-face :inherit ,font-lock-warning-face)
               ;; which-func
               (which-func :inherit ,font-lock-function-name-face)
               ;; whitespace
               (whitespace-big-indent :background ,christmas-red :foreground ,christmas-red)
               (whitespace-empty :background ,christmas-orange :foreground ,christmas-red)
               (whitespace-hspace :background ,bg3 :foreground ,christmas-comment)
               (whitespace-indentation :background ,christmas-orange :foreground ,christmas-red)
               (whitespace-line :background ,christmas-bg :foreground ,christmas-pink)
               (whitespace-newline :foreground ,christmas-comment)
               (whitespace-space :background ,christmas-bg :foreground ,christmas-comment)
               (whitespace-space-after-tab :background ,christmas-orange :foreground ,christmas-red)
               (whitespace-space-before-tab :background ,christmas-orange :foreground ,christmas-red)
               (whitespace-tab :background ,bg2 :foreground ,christmas-comment)
               (whitespace-trailing :inherit trailing-whitespace)
               ;; yard-mode
               (yard-tag-face :inherit ,font-lock-builtin-face)
               (yard-directive-face :inherit ,font-lock-builtin-face))))

  (apply #'custom-theme-set-faces
         'christmas
         (let ((color-names (mapcar #'car colors))
               (graphic-colors (mapcar #'cadr colors))
               (tty-colors (mapcar #'car (mapcar #'last colors))))
           (cl-flet* ((expand-for-tty (spec) (cl-progv color-names tty-colors
                                               (eval `(backquote ,spec))))
                      (expand-for-graphic (spec) (cl-progv color-names graphic-colors
                                                   (eval `(backquote ,spec)))))
             (cl-loop for (face . spec) in faces
                      collect `(,face
                                ((((min-colors 16777216))
                                  ,(expand-for-graphic spec))
                                 (t
                                  ,(expand-for-tty spec)))))))))

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'christmas)

;; Local Variables:
;; no-byte-compile: t
;; indent-tabs-mode: nil
;; End:

;;; christmas-theme.el ends here
